INSERT INTO TB_SET_WSETMATCH (WSETNO, PLATSYSID, WARECLASS, WARECLASSNAME, WAREID, WARENAME, B_FIRMID, S_FIRMID, WAREKINDID, WAREKINDNAME, SETPRICE, WSETNUM, SETMONEY, WSETDATE) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_SET_WSETMATCHDTL (WSETNO, CONTTYPE, JLUNIT, BDATE, SDATE) VALUES (NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_SET_WSETMATCH (WSETNO, PLATSYSID, WARECLASS, WARECLASSNAME, WAREID, WARENAME, B_FIRMID, S_FIRMID, WAREKINDID, WAREKINDNAME, SETPRICE, WSETNUM, SETMONEY, WSETDATE) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TB_SET_WSETMATCHDTL (WSETNO, CONTTYPE, JLUNIT, BDATE, SDATE) VALUES (NULL, NULL, NULL, NULL, NULL);
